### PR TITLE
Add libgpustats libraries as modules.

### PR DESCRIPTION
**Pull request by hacker1024**
This is needed to build.

### CODE REVIEW

**Comment by luk1337** [comment]
No it's not. Use AOSP media HAL.

**Comment by hacker1024** [comment]
How? Using sources straight from here, the build fails. Shouldn't it be configured in this repo to use the the AOSP Media HAL?

**Comment by luk1337** [comment]
Check latest open changes on 15.1.

**Comment by lineageos-gerrit** [comment]
Hi there;
This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by hacker1024** [comment]
image
I don't see any relevant patches? Can you please link the one you used?

**Comment by luk1337** [comment]
Wrong branch.

**Comment by hacker1024** [comment]
Oh, which one?

**Comment by luk1337** [comment]
The one this repo is on.

**Comment by hacker1024** [comment]
Ah, got it, thanks.

**Pull request closed without merging**
