### PR TITLE
Merge pull request #1 from LineageOS/cm-14.1

### PR DESCRIPTION
**Pull request by NexusPenguin**
Keep up to date

### CODE REVIEW

**Comment by luca020400** [comment]
Merge failed. Please try later.

**Comment by NexusPenguin** [comment]
Hi,

Sorry… Made a mistake and pulled from me to you instead of the other way round ☹
I’m kind of a noob ☹

But hey… since you are there.
I think that patch 8 of the gerrit breaks things.

I’ve built a ROM with patch 8 => adreno oom errors ;
Same ROM with patch 7 => no errors.

Maybe you are already aware of this…
If so, please forgive me ☹
If not, maybe you can look into it !

And thanks for all your work !
It’s great to have custom ROM’s on the Natrium ☺

Regards.

De : Luca Stefani <notifications@github.com>
Répondre à : LineageOS/android_device_xiaomi_natrium <reply@reply.github.com>
Date : dimanche 23 avril 2017 à 13:49
À : LineageOS/android_device_xiaomi_natrium <android_device_xiaomi_natrium@noreply.github.com>
Cc : Fred <fredbottaro.alva@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [LineageOS/android_device_xiaomi_natrium] Merge pull request #1 from LineageOS/cm-14.1 (#4)


Merge failed. Please try later.

**Comment by luk1337** [comment]
>I’ve built a ROM with patch 8 => adreno oom errors ;
>Same ROM with patch 7 => no errors.

Whatever `patch 8` and `patch 7` is supposed to mean...

**Comment by NexusPenguin** [comment]
Hi Luk1337,

Sorry if what I said was not explicit :

https://review.lineageos.org/#/c/165050/

I’m talking about this.
Patch 8 is the latest from April 15th.
Patch 7 is the previous from March 31.

All ROMs I’ve built with patch 8 have the same behavior.
If I play “Transformers Iron Forged”, the game FC’s after a battle.
I’ve played while phone was connected to computer and running “adb logcat” in Terminal.
It turned out that this was caused by “adreno out of memory” errors.

Besides, if I install Substratum : phone display doesn’t go to sleep ☹

None of these errors appear if I build the exact same ROM but use the patch 7 from March 31.

I’m only trying to help to get a better device… but I am not a developer.
Sorry if I do not use the correct terms.

Regards.

FRED

De : luk1337 <notifications@github.com>
Répondre à : LineageOS/android_device_xiaomi_natrium <reply@reply.github.com>
Date : dimanche 23 avril 2017 à 23:00
À : LineageOS/android_device_xiaomi_natrium <android_device_xiaomi_natrium@noreply.github.com>
Cc : Fred <fredbottaro.alva@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [LineageOS/android_device_xiaomi_natrium] Merge pull request #1 from LineageOS/cm-14.1 (#4)


I’ve built a ROM with patch 8 => adreno oom errors ;
Same ROM with patch 7 => no errors.

Whatever patch 8 and patch 7 is supposed to mean...

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by luk1337** [comment]
>Besides, if I install Substratum : phone display doesn’t go to sleep ☹

This doesn't make a lot of sense, I use self patched Lineage builds and it works just fine.

**Comment by NexusPenguin** [comment]
Hi,

Thanks for your answer.

As I said : I am not a developer ☹
So sorry if I am talking things that do not make much sense.

But what I told you is systematic and totally reproductible.
So maybe something wrong with Slim and AOSP based ROMs ?

By the way : I’ve seen you uploaded patch 9.
Will give that one a try.

Interested in the reports ?

Regards.

FRED



De : luk1337 <notifications@github.com>
Répondre à : LineageOS/android_device_xiaomi_natrium <reply@reply.github.com>
Date : lundi 24 avril 2017 à 09:47
À : LineageOS/android_device_xiaomi_natrium <android_device_xiaomi_natrium@noreply.github.com>
Cc : Fred <fredbottaro.alva@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [LineageOS/android_device_xiaomi_natrium] Merge pull request #1 from LineageOS/cm-14.1 (#4)


Besides, if I install Substratum : phone display doesn’t go to sleep ☹

This doesn't make a lot of sense, I use self patched Lineage builds and it works just fine.

**Comment by luk1337** [comment]
No, I am not interested in helping with other roms.

**Comment by NexusPenguin** [comment]
Hi,

OK.
Wasn’t asking for help…
Just in giving a report.

But as you don’t want it, so be it.

Have a nice day.

Regards.

De : luk1337 <notifications@github.com>
Répondre à : LineageOS/android_device_xiaomi_natrium <reply@reply.github.com>
Date : lundi 24 avril 2017 à 10:30
À : LineageOS/android_device_xiaomi_natrium <android_device_xiaomi_natrium@noreply.github.com>
Cc : Fred <fredbottaro.alva@gmail.com>, Author <author@noreply.github.com>
Objet : Re: [LineageOS/android_device_xiaomi_natrium] Merge pull request #1 from LineageOS/cm-14.1 (#4)


No, I am not interested in helping with other roms.

**Pull request closed without merging**
